name: Default
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Grab version
        id: version
        run: |
          echo "::set-output name=semver::$(cat version)"
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          args: |
            VERSION=${{ steps.version.outputs.semver }}
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/dyndns:${{ steps.version.outputs.semver }}